### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by inzi119** [otissv/react-uikit-components#10]
i imported button as
import Button from 'react-uikit-button';
then in render method i used the button component
render(){
....
<Button size='large' body='Large button' margin='right bottom'/>
....
}

but i get a regular html button with no styling

**Comment by Charliekenney23** [comment]
Working just fine for me:
<br>
![test](https://i.imgur.com/FLoKkQ6.jpg)

Are you sure you didn't accidentally call it <button> (html reserved) or forget to include the UIKit stylesheet?

stylesheet:
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.21.0/css/uikit.min.css" />
```

**Comment by otissv** [comment]
@inzi119 Have you tried @Charliekenney23 suggestions? UIKit CSS framework is not included in the module and must be added to your html page. You can find more information at https://getuikit.com/docs/installation#download

**Comment by inzi119** [comment]
after installing uikit i only get the relevent color but not other styles.

![capture](https://user-images.githubusercontent.com/15038177/28635495-6c099550-7258-11e7-9a38-b9238f55b122.PNG)

`import Alert from 'react-uikit-alert';
import Button from 'react-uikit-button';

render(){
..
<Button context='danger' body='Danger' margin='bottom right'/>
<Alert show context='danger'>	Message</Alert>				
..}`

**Comment by otissv** [comment]
Could you show your full code for the alert and button components as they seem to be displaying correctly given your screenshot?

What styles are missing?

Posibble reasons:
1) It could be the uikit.min.css you that only give the minimum of styling. 
UIKit CSS also comes with "almost flat: and "gradient". 
2) Check you have the correct version of UIKit installed. 
react-uikit-component supports version 2 of UIKit CSS. Version 3 beta is not yet supported.
