### ISSUE TITLE
Node 6?

### ISSUE THREAD

**Issue by kapooostin** [otissv/react-uikit-components#4]
The package refused to install on my system with `nodejs v. 6`. It this dependency critical for `react-uikit-components`?

**Comment by otissv** [comment]
I'm running node v6+ and it runs.  Also tested on v4.4+ and v5+.

However this is only the documentation module. If you are after the components and not docs, each component has it's own individual package, which is the recommended way to install.

**Comment by kapooostin** [comment]
I tried to install `react-uikit-button` and decided to file an issue here
in a common repo.
Well, `npm` installs it but `yarn` does not because of mismatched `nodejs`
version.

**Comment by otissv** [comment]
I have not tested any components with yarn (or used yarn) but at a guess it is probably to do with the engines set to "~4.4.5"

**Comment by kapooostin** [comment]
Yes, that is exactly the reason.

**Comment by otissv** [comment]
When react moves to the next release I will remove engines from the package.json for all components

**Comment by kapooostin** [comment]
React itself is not restricted to `node 4.x`:
https://github.com/facebook/react/blob/15-stable/package.json#L72.

**Comment by otissv** [comment]
React uikit components was not restricted to node 4.x under npm. It installed under all versions of npm and node. This is due to how yarn works. I understand people will start installing it with yarn so the engines should be removed or changed and tested under yarn.

**Comment by otissv** [comment]
Removed the engines property from all the modules packages. Should have any issues installing with yarn now.
