### ISSUE TITLE
Broken docs

### ISSUE THREAD

**Issue by mayasd** [otissv/react-uikit-components#5]
Hi,

I am a beginner in React and React-router so I can't explain (for the moment) clearly why modifications which I made fix the doc.

I modified two files. First in **src/routes.jsx** line number 132 : 

replace `path: '/docs.html',` with `path: '/',`

And in **src/app.js** line number 15 : 

replace `history={browserHistory}` with `history={hashHistory}`

Don't forget to import **hashHistory** line 4.

After `npm run build` docs is available.

**Comment by otissv** [comment]
Thanks. That fixed the docs.
